import type { Staff, Patient, Appointment } from "./types"

export const mockStaff: Staff[] = [
  {
    id: "1",
    clinic_id: "1",
    name: "今泉 太郎",
    role: "doctor",
    email: "taro@imaizumi-dental.jp",
    phone: "090-1234-5678",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    clinic_id: "1",
    name: "山田 花子",
    role: "hygienist",
    email: "hanako@imaizumi-dental.jp",
    phone: "090-2345-6789",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    clinic_id: "1",
    name: "佐藤 次郎",
    role: "doctor",
    email: "jiro@imaizumi-dental.jp",
    phone: "090-3456-7890",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockPatients: Patient[] = [
  {
    id: "1",
    clinic_id: "1",
    patient_number: "P001",
    name: "田中 太郎",
    kana: "タナカ タロウ",
    date_of_birth: "1980-05-15",
    gender: "男性",
    phone: "090-1111-2222",
    email: "tanaka@example.com",
    address: "東京都渋谷区xxx",
    allergies: ["ペニシリン"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    clinic_id: "1",
    patient_number: "P002",
    name: "山田 花子",
    kana: "ヤマダ ハナコ",
    date_of_birth: "1992-08-22",
    gender: "女性",
    phone: "090-2222-3333",
    email: "yamada@example.com",
    address: "東京都新宿区xxx",
    allergies: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "1",
    clinic_id: "1",
    patient_id: "1",
    staff_id: "1",
    date: "2024-01-15",
    start_time: "09:00",
    end_time: "09:30",
    treatment_type: "定期検診",
    status: "confirmed",
    chair_number: 1,
    notes: "",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    patient: { name: "田中 太郎", phone: "090-1111-2222" },
    staff: { name: "今泉 太郎" },
  },
  {
    id: "2",
    clinic_id: "1",
    patient_id: "2",
    staff_id: "2",
    date: "2024-01-15",
    start_time: "10:00",
    end_time: "11:00",
    treatment_type: "虫歯治療",
    status: "confirmed",
    chair_number: 2,
    notes: "",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    patient: { name: "山田 花子", phone: "090-2222-3333" },
    staff: { name: "山田 花子" },
  },
]
